.\" This is a comment
.\" Contact @yokofakun
.TH make2graph 1 "17 Sept 2014" ".1" "Creates a graph of dependencies from GNU-Make"
.SH NAME
makefile2graph \- Creates a graph of dependencies from GNU-Make
.SH SYNOPSIS
make -Bnd | make2graph > output.dot
.SH DESCRIPTION
Creates a graph of dependencies from GNU-Make; Output is a graphiz-dot file or a Gexf-XML file. sub-makefiles are not supported.
.SH OPTIONS
.TP
.B \-\^f 
formats :(x) XML output (gexf), (E) print a list of deepest targets, (l) print a list of targets, (d) dot output (default)
.TP
.B \-\^b
print file basename
.TP
.B \-\^s 
print file extension
.TP
.B \-\^r
show root node
.TP
.B \-\^v
print version
.SH SEE ALSO
makefile2graph(1), make(1), dot(1)
.SH AUTHOR
Pierre Lindenbaum (@yokofakun)
